# Random_Forest_Assignment_(Company_Data)

In [1]:
# Import Libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing

In [5]:
#Importing dataset
df=pd.read_csv('C:/Users/Akash Kundu/Desktop/ExcelR/Assingments/Company_Data (1).csv')
df

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

### EDA

In [6]:
df.loc[df.Sales>=8.5,'sales']='High'
df.loc[df.Sales<8.5,'sales']='Low'

In [7]:
df

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US sales  
0           17   Yes  Yes  High  
1           10   Yes  Yes  High  
2           12   Yes  Yes  High  
3           14   Yes  Yes   Low  
4           13   Yes   No   Low  
..         ...   ...  ...   ...  
395         14   Yes  Yes  High  
396         11    No  Yes   Low  
397         18   Yes  Yes   Low  
398         12   Yes  Yes   Low  
399         16   Yes  Yes  High  

[400 rows x 12 columns]

In [8]:
df.drop('Sales',inplace=True,axis=1)

In [9]:
df

CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0          138      73           11         276    120       Bad   42   
1          111      48           16         260     83      Good   65   
2          113      35           10         269     80    Medium   59   
3          117     100            4         466     97    Medium   55   
4          141      64            3         340    128       Bad   38   
..         ...     ...          ...         ...    ...       ...  ...   
395        138     108           17         203    128      Good   33   
396        139      23            3          37    120    Medium   55   
397        162      26           12         368    159    Medium   40   
398        100      79            7         284     95       Bad   50   
399        134      37            0          27    120      Good   49   

     Education Urban   US sales  
0           17   Yes  Yes  High  
1           10   Yes  Yes  High  
2           12   Yes  Yes  High  
3           14   Yes  Yes   Low  
4           13   Yes   No   Low  
..         ...   ...  ...   ...  
395         14   Yes  Yes  High  
396         11    No  Yes   Low  
397         18   Yes  Yes   Low  
398         12   Yes  Yes   Low  
399         16   Yes  Yes  High  

[400 rows x 11 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   CompPrice    400 non-null    int64 
 1   Income       400 non-null    int64 
 2   Advertising  400 non-null    int64 
 3   Population   400 non-null    int64 
 4   Price        400 non-null    int64 
 5   ShelveLoc    400 non-null    object
 6   Age          400 non-null    int64 
 7   Education    400 non-null    int64 
 8   Urban        400 non-null    object
 9   US           400 non-null    object
 10  sales        400 non-null    object
dtypes: int64(7), object(4)
memory usage: 34.5+ KB


In [11]:
df.isna().sum()

CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
sales          0
dtype: int64

In [12]:
#finding Unique values and convert these catagorical values into numerical values
df.ShelveLoc.unique()

array(['Bad', 'Good', 'Medium'], dtype=object)

In [13]:
df['ShelveLoc']=preprocessing.LabelEncoder().fit_transform(df['ShelveLoc'])

In [14]:
df.Urban.unique()

array(['Yes', 'No'], dtype=object)

In [17]:
df['Urban']=preprocessing.LabelEncoder().fit_transform(df['Urban'])

In [19]:
df.US.unique()

array(['Yes', 'No'], dtype=object)

In [20]:
df['US']=preprocessing.LabelEncoder().fit_transform(df['US'])

In [21]:
df.sales.unique()

array(['High', 'Low'], dtype=object)

In [22]:
df['sales']=preprocessing.LabelEncoder().fit_transform(df['sales'])

In [23]:
df

CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0          138      73           11         276    120          0   42   
1          111      48           16         260     83          1   65   
2          113      35           10         269     80          2   59   
3          117     100            4         466     97          2   55   
4          141      64            3         340    128          0   38   
..         ...     ...          ...         ...    ...        ...  ...   
395        138     108           17         203    128          1   33   
396        139      23            3          37    120          2   55   
397        162      26           12         368    159          2   40   
398        100      79            7         284     95          0   50   
399        134      37            0          27    120          1   49   

     Education  Urban  US  sales  
0           17      1   1      0  
1           10      1   1      0  
2           12      1   1      0  
3           14      1   1      1  
4           13      1   0      1  
..         ...    ...  ..    ...  
395         14      1   1      0  
396         11      0   1      1  
397         18      1   1      1  
398         12      1   1      1  
399         16      1   1      0  

[400 rows x 11 columns]

In [28]:
#devide the data into target and predectors
columns=list(df.columns)
predictors=columns[0:10]
target=columns[-1]

In [29]:
predictors

['CompPrice',
 'Income',
 'Advertising',
 'Population',
 'Price',
 'ShelveLoc',
 'Age',
 'Education',
 'Urban',
 'US']

In [30]:
target

'sales'

In [31]:
X=df[predictors]
Y=df[target]

### Model Building

In [33]:
RF=RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion='entropy')
RF

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

### Model prediction

In [34]:
RF.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [35]:
RF.estimators_

[DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1249956091),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=889094573),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1982338666),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=2040995824),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1018086251),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=223421431),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1452440929),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=823403314),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
         

In [36]:
RF.classes_

array([0, 1])

In [37]:
RF.n_features_

10

In [38]:
RF.n_outputs_

1

In [39]:
df['rf_redict']=RF.predict(X)

In [40]:
confusion_matrix(df['sales'],df['rf_redict'])

array([[143,   0],
       [  0, 257]], dtype=int64)

### Now will try with 500 decision tress

In [41]:
RF=RandomForestClassifier(n_jobs=2,n_estimators=500,oob_score=True,criterion='entropy')

In [42]:
RF.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=500, n_jobs=2,
                       oob_score=True)

In [43]:
df['rf_predict2']=RF.predict(X)

In [44]:
confusion_matrix(df['sales'],df['rf_predict2'])

array([[143,   0],
       [  0, 257]], dtype=int64)